option gurobi_options 'presolve=2 iis=1 outlev=1';

option presolve 0;
option show_stats 2;

display given;

solve;

# display X;

printf "\n";
printf "Sudoku Solution\n";
printf "===============\n";

printf "   ";
for {j in COLS} printf "%2d ", j;
printf "\n";


for {i in ROWS} {
    printf "%2d ", i;
    for {j in COLS} {
            printf "%2d ", X[i, j];
    }
    printf "\n";
}
printf "\n";
